<a href="https://colab.research.google.com/github/SWLee1212/TensorFlow-in-Practice/blob/master/Exercise_8_Question(load_csv_file).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import csv
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from google.colab import files

The data for this exercise is available at: https://www.kaggle.com/datamunge/sign-language-mnist/home

Sign up and download to find 2 CSV files: sign_mnist_test.csv and sign_mnist_train.csv -- You will upload both of them using this button before you can continue.


In [0]:
uploaded=files.upload()

Saving sign_mnist_test.csv to sign_mnist_test.csv
Saving sign_mnist_train.csv to sign_mnist_train.csv


In [0]:
def get_data(filename):
  # You will need to write code that will read the file passed
  # into this function. The first line contains the column headers
  # so you should ignore it
  # Each successive line contians 785 comma separated values between 0 and 255
  # The first value is the label
  # The rest are the pixel values for that picture
  # The function will return 2 np.array types. One with all the labels
  # One with all the images
  #
  # Tips: 
  # If you read a full line (as 'row') then row[0] has the label
  # and row[1:785] has the 784 pixel values
  # Take a look at np.array_split to turn the 784 pixels into 28x28
  # You are reading in strings, but need the values to be floats
  # Check out np.array().astype for a conversion
    images = []
    labels = []

    with open(filename) as training_file:
      # Your code starts here
      data = csv.reader(training_file)
      isFirst_Line = True

      loop_index = 0;
      for row in data:
        # if loop_index == 1:  
        #   print(type(row[0]),len(row[1:]))
        # loop_index += 1  
        if isFirst_Line :
          isFirst_Line = False
        else:
          labels.append(row[0])
          images.append(np.array_split(row[1:],28))
          # images.append(row[1:])

      labels = np.array(labels).astype(float)
      images = np.array(images).astype(float)

      # Your code ends here
    return images, labels


training_images, training_labels = get_data('sign_mnist_train.csv')
testing_images, testing_labels = get_data('sign_mnist_test.csv')

# # Keep these
print(training_images.shape)
print(training_labels.shape)
print(testing_images.shape)
print(testing_labels.shape)

# Their output should be:
# (27455, 28, 28)
# (27455,)
# (7172, 28, 28)
# (7172,)

(27455, 28, 28)
(27455,)
(7172, 28, 28)
(7172,)


In [0]:
# print(training_images[0])
print(training_images[0])

[[107. 118. 127. 134. 139. 143. 146. 150. 153. 156. 158. 160. 163. 165.
  159. 166. 168. 170. 170. 171. 171. 171. 172. 171. 171. 170. 170. 169.]
 [111. 121. 129. 135. 141. 144. 148. 151. 154. 157. 160. 163. 164. 170.
  119. 152. 171. 171. 170. 171. 172. 172. 172. 172. 172. 171. 171. 170.]
 [113. 123. 131. 137. 142. 145. 150. 152. 155. 158. 161. 163. 164. 172.
  105. 142. 170. 171. 171. 171. 172. 172. 173. 173. 172. 171. 171. 171.]
 [116. 125. 133. 139. 143. 146. 151. 153. 156. 159. 162. 163. 167. 167.
   95. 144. 171. 172. 172. 172. 172. 172. 173. 173. 173. 172. 172. 171.]
 [117. 126. 134. 140. 145. 149. 153. 156. 158. 161. 163. 164. 175. 156.
   87. 154. 172. 173. 173. 173. 173. 173. 174. 174. 174. 173. 172. 172.]
 [119. 128. 136. 142. 146. 150. 153. 156. 159. 163. 165. 164. 184. 148.
   89. 164. 172. 174. 174. 174. 174. 175. 175. 174. 175. 174. 173. 173.]
 [122. 130. 138. 143. 147. 150. 154. 158. 162. 165. 166. 172. 181. 128.
   94. 170. 173. 175. 174. 175. 176. 177. 177. 177. 177. 1

In [0]:
x = np.array([[1,2,3,4],[8,5,6,7]])
x1 = np.expand_dims(x,axis=-1)
print(x.shape)
print(x1)
print(x1.shape)

y = np.array([1,2,3,4])
print(np.expand_dims(y,axis=0))

(2, 4)
[[[1]
  [2]
  [3]
  [4]]

 [[8]
  [5]
  [6]
  [7]]]
(2, 4, 1)
[[1 2 3 4]]


In [0]:
# In this section you will have to add another dimension to the data
# So, for example, if your array is (10000, 28, 28)
# You will need to make it (10000, 28, 28, 1)
# Hint: np.expand_dims

training_images = np.expand_dims(training_images,axis=-1)
testing_images = np.expand_dims(testing_images,axis=-1)

# print(training_images[0])

# Create an ImageDataGenerator and do Image Augmentation
train_datagen = ImageDataGenerator(
            rescale=1.0/255.,
            rotation_range = 40,
            width_shift_range=0.2,
            height_shift_range=0.2,
            shear_range = 0.2,
            zoom_range=0.2,
            horizontal_flip=True)


validation_datagen = ImageDataGenerator(rescale = 1.0/255. )
    
# Keep These
print(training_images.shape)
print(testing_images.shape)


# Their output should be:
# (27455, 28, 28, 1)
# (7172, 28, 28, 1)

(27455, 28, 28, 1)
(7172, 28, 28, 1)


In [0]:
# Define the model
# Use no more than 2 Conv2D and 2 MaxPooling2D
model = tf.keras.models.Sequential([
   # The First Layer
   tf.keras.layers.Conv2D(32,(3,3),activation='relu', input_shape = (28,28,1)),
   tf.keras.layers.MaxPooling2D(2,2),

   # The Second Layer
   tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
   tf.keras.layers.MaxPooling2D(2,2),

   tf.keras.layers.Flatten(),
   tf.keras.layers.Dense(512, activation='relu'),
   tf.keras.layers.Dense(26, activation='softmax')]
    )

# Compile Model. 
model.compile(loss='sparse_categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

# Train the Model
history = model.fit_generator(train_datagen.flow(training_images,training_labels, batch_size = 32),
                              steps_per_epoch = len(training_images) / 32 , 
                              epochs= 20,
                              validation_data = validation_datagen.flow(testing_images,testing_labels, batch_size=32),
                              validation_steps= len(testing_images) / 32
                              )

model.evaluate(testing_images, testing_labels)
    
# The output from model.evaluate should be close to:
[6.92426086682151, 0.56609035]


Epoch 1/20
858/857 [==============================] - 42s 49ms/step - loss: 2.6106 - acc: 0.2023 - val_loss: 1.5180 - val_acc: 0.5100
Epoch 2/20
858/857 [==============================] - 41s 48ms/step - loss: 1.8075 - acc: 0.4274 - val_loss: 1.2630 - val_acc: 0.5605
Epoch 3/20
858/857 [==============================] - 41s 48ms/step - loss: 1.3500 - acc: 0.5590 - val_loss: 0.9328 - val_acc: 0.6669
Epoch 4/20
858/857 [==============================] - 41s 48ms/step - loss: 1.0809 - acc: 0.6437 - val_loss: 0.6473 - val_acc: 0.7715
Epoch 5/20
858/857 [==============================] - 41s 48ms/step - loss: 0.8913 - acc: 0.7044 - val_loss: 0.4514 - val_acc: 0.8314
Epoch 6/20
858/857 [==============================] - 42s 48ms/step - loss: 0.7569 - acc: 0.7491 - val_loss: 0.2730 - val_acc: 0.9090
Epoch 7/20
858/857 [==============================] - 41s 48ms/step - loss: 0.6530 - acc: 0.7823 - val_loss: 0.2286 - val_acc: 0.9276
Epoch 8/20
858/857 [==============================] - 41s 48ms

[6.92426086682151, 0.56609035]

In [0]:
# Plot the chart for accuracy and loss on both training and validation

import matplotlib.pyplot as plt
acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'r', label='Training accuracy')
plt.plot(epochs, val_acc, 'b', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.legend()
plt.figure()

plt.plot(epochs, loss, 'r', label='Training Loss')
plt.plot(epochs, val_loss, 'b', label='Validation Loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

In [0]:
from plotly import __version__
print(__version__)

4.1.1


In [0]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [0]:

fig = make_subplots(
    rows=1,cols=2,
    subplot_titles=('Accuracy','Loss')
    )

fig.add_trace(
    go.Scatter(x=list(epochs), y=acc, name='train acc'),
    row=1,col=1
    )
fig.add_trace(
    go.Scatter(x=list(epochs), y=val_acc, name='val acc'),
    row=1, col=1)        

fig.add_trace(
    go.Scatter(x=list(epochs), y=loss, name='train loss'),
    row=1, col=2)
fig.add_trace(
    go.Scatter(x=list(epochs), y=val_loss, name='val loss'),
    row=1,col=2)        

fig.update_xaxes(title_text = 'epoch',row=1,col=1)
fig.update_xaxes(title_text = 'epoch',row=1,col=2)
fig.update_yaxes(title_text = 'accuracy',row=1,col=1)
fig.update_yaxes(title_text = 'loss',row=1,col=2)

fig.update_layout(title_text='conv1 filter_len =16, conv2 filter_len=32')
fig.show()

In [0]:
fig = make_subplots(
    rows=1,cols=2,
    subplot_titles=('Accuracy','Loss')
    )

fig.add_trace(
    go.Scatter(x=list(epochs), y=acc, name='train acc'),
    row=1,col=1
    )
fig.add_trace(
    go.Scatter(x=list(epochs), y=val_acc, name='val acc'),
    row=1, col=1)        

fig.add_trace(
    go.Scatter(x=list(epochs), y=loss, name='train loss'),
    row=1, col=2)
fig.add_trace(
    go.Scatter(x=list(epochs), y=val_loss, name='val loss'),
    row=1,col=2)        

fig.update_xaxes(title_text = 'epoch',row=1,col=1)
fig.update_xaxes(title_text = 'epoch',row=1,col=2)
fig.update_yaxes(title_text = 'accuracy',row=1,col=1)
fig.update_yaxes(title_text = 'loss',row=1,col=2)

fig.update_layout(title_text='conv1 filter_len =32, conv2 filter_len=64')
fig.show()