<a href="https://colab.research.google.com/github/SWLee1212/TensorFlow-in-Practice/blob/master/tensorflow_dataset_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
print(tf.__version__)
tf.enable_eager_execution()

1.15.0


In [0]:

dataset = tf.data.Dataset.range(1,4)

In [0]:
data_iter = dataset.__iter__()

In [0]:
for d in data_iter:
  print(d)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [0]:
data_iter = dataset.__iter__()


for d in data_iter:
  print(d)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [0]:

X = tf.constant([[[1,2,3],[3,4,5]],[[3,4,5],[5,6,7]]])
Y = tf.constant([[[11]],[[12]]])
dataset = tf.data.Dataset.from_tensor_slices((X, Y))
for x, y in dataset:
  print(x, y)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32) tf.Tensor([[11]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[3 4 5]
 [5 6 7]], shape=(2, 3), dtype=int32) tf.Tensor([[12]], shape=(1, 1), dtype=int32)


In [0]:
import numpy as np

x = np.random.sample((100,2))
# make a dataset from a numpy array
dataset = tf.data.Dataset.from_tensor_slices(x)
# create the iterator
iter = dataset.make_one_shot_iterator()

Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.


In [0]:
# create the iterator
iter = dataset.make_one_shot_iterator()
el = iter.get_next()

In [0]:


for x,l in dataset:
  print(x, l)

tf.Tensor(0.3933147545566097, shape=(), dtype=float64) tf.Tensor(0.8787389237617256, shape=(), dtype=float64)
tf.Tensor(0.44869158376202734, shape=(), dtype=float64) tf.Tensor(0.46061555674676513, shape=(), dtype=float64)
tf.Tensor(0.20460810663492612, shape=(), dtype=float64) tf.Tensor(0.373740171316978, shape=(), dtype=float64)
tf.Tensor(0.45259045403525255, shape=(), dtype=float64) tf.Tensor(0.8442150179320242, shape=(), dtype=float64)
tf.Tensor(0.05705703395656281, shape=(), dtype=float64) tf.Tensor(0.9703355053525193, shape=(), dtype=float64)
tf.Tensor(0.8698631948435814, shape=(), dtype=float64) tf.Tensor(0.12597460172589936, shape=(), dtype=float64)
tf.Tensor(0.40378152855513316, shape=(), dtype=float64) tf.Tensor(0.974805158139165, shape=(), dtype=float64)
tf.Tensor(0.3758984363989465, shape=(), dtype=float64) tf.Tensor(0.0720708880189852, shape=(), dtype=float64)
tf.Tensor(0.07242718005731885, shape=(), dtype=float64) tf.Tensor(0.3572192586153323, shape=(), dtype=float64)
tf.T

In [0]:
data_batch = dataset.batch(4)

for d in data_batch:
  print(d)

tf.Tensor(
[[0.39331475 0.87873892]
 [0.44869158 0.46061556]
 [0.20460811 0.37374017]
 [0.45259045 0.84421502]], shape=(4, 2), dtype=float64)
tf.Tensor(
[[0.05705703 0.97033551]
 [0.86986319 0.1259746 ]
 [0.40378153 0.97480516]
 [0.37589844 0.07207089]], shape=(4, 2), dtype=float64)
tf.Tensor(
[[0.07242718 0.35721926]
 [0.08365527 0.94547028]
 [0.20817122 0.98419048]
 [0.73088253 0.08794034]], shape=(4, 2), dtype=float64)
tf.Tensor(
[[0.86135949 0.69484822]
 [0.29283521 0.30070834]
 [0.597288   0.27889877]
 [0.61356344 0.49339559]], shape=(4, 2), dtype=float64)
tf.Tensor(
[[0.32982256 0.19797749]
 [0.90890351 0.49076918]
 [0.83490552 0.04341028]
 [0.67678089 0.28890703]], shape=(4, 2), dtype=float64)
tf.Tensor(
[[0.76048267 0.94057162]
 [0.0033302  0.81881385]
 [0.30834761 0.02777739]
 [0.02818739 0.4764257 ]], shape=(4, 2), dtype=float64)
tf.Tensor(
[[0.35342673 0.630018  ]
 [0.33020112 0.96227524]
 [0.55889976 0.92108702]
 [0.14547366 0.04822678]], shape=(4, 2), dtype=float64)
tf.Ten